<a href="https://colab.research.google.com/github/zain4cs/Unsupervised_Learning/blob/main/Cross_validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [ ]:
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

_________

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = df.drop('species', axis=1)
y = df['species']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
model_knn = KNeighborsClassifier(n_neighbors=5)
model_knn.fit(X_train, y_train)
# y_pred_knn = model_knn.predict(X_test)

KNeighborsClassifier()

In [ ]:
model_knn.score(X_test, y_test)

1.0

**Now use SVM**

In [ ]:
from sklearn.svm import SVC

In [ ]:
model_svm = SVC(gamma='auto')
model_svm.fit(X_train, y_train)
model_svm.score(X_test, y_test)

1.0

___________________________

**Grid Search CV**

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
grid = GridSearchCV((model_svm),{
    'C': [1,10, 20, 30],
    'kernel': ['rbf', 'linear'],
    }, cv=5, return_train_score=False)

In [ ]:
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [ ]:
grid.cv_results_

{'mean_fit_time': array([0.00798135, 0.00607276, 0.00970211, 0.00773711, 0.00767331,
        0.00761294, 0.01260128, 0.00835977]),
 'std_fit_time': array([0.00279655, 0.00196799, 0.00219423, 0.0004229 , 0.00204513,
        0.00121643, 0.00321271, 0.00094909]),
 'mean_score_time': array([0.00532603, 0.004738  , 0.00696893, 0.00669456, 0.00541081,
        0.00668387, 0.00805883, 0.00574207]),
 'std_score_time': array([0.00157055, 0.00162932, 0.00225565, 0.00249736, 0.00127738,
        0.00100164, 0.00275933, 0.00110128]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([1.        , 1.        , 1.        , 1.        , 0.95833333,
        0.95833333, 0.95833333, 0.95833333]),
 'split1_test_score': array([0.95833333, 0.95833333, 0.95833333, 0.95833333, 0.95833333,
        0.95833333, 0.95833333, 0.95833333]),
 'split2_test_score': array([0.83333333, 0.875     , 0.83333333, 0.83333333, 0.83333333,
        0.83333333, 0.83333333, 0.83333333]),
 'split3_test_score': array([1.        , 1.        , 1.        , 0.95833333, 1.        ,
        1.        , 1.        , 0.95833333]),
 'split4_test_score': array([0.95833333, 0.95833333, 1.        , 1.        , 1.        ,
        1.        , 0.95833333, 1.        ]),
 'mean_test_score': array([0.95      , 0.95833333, 0.95833333, 0.95      , 0.95      ,
        0.95      , 0.94166667, 0.94166667]),
 'std_test_score': array([0.06123724, 0.04564355, 0.06454972, 0.06123724, 0.06123724,
        0.06123724, 0.05651942, 0.05651942]),
 'rank_test_score': array([3, 1, 1, 3, 3, 3, 8, 7], dtype=int32)}

In [ ]:
results = pd.DataFrame(grid.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.007981,0.002797,0.005326,0.001571,1,rbf,"{'C': 1, 'kernel': 'rbf'}",1.000000,0.958333,0.833333,1.000000,0.958333,0.950000,0.061237,3
1,0.006073,0.001968,0.004738,0.001629,1,linear,"{'C': 1, 'kernel': 'linear'}",1.000000,0.958333,0.875000,1.000000,0.958333,0.958333,0.045644,1
2,0.009702,0.002194,0.006969,0.002256,10,rbf,"{'C': 10, 'kernel': 'rbf'}",1.000000,0.958333,0.833333,1.000000,1.000000,0.958333,0.064550,1
3,0.007737,0.000423,0.006695,0.002497,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,0.958333,0.833333,0.958333,1.000000,0.950000,0.061237,3
4,0.007673,0.002045,0.005411,0.001277,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.958333,0.958333,0.833333,1.000000,1.000000,0.950000,0.061237,3
5,0.007613,0.001216,0.006684,0.001002,20,linear,"{'C': 20, 'kernel': 'linear'}",0.958333,0.958333,0.833333,1.000000,1.000000,0.950000,0.061237,3
6,0.012601,0.003213,0.008059,0.002759,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.958333,0.958333,0.833333,1.000000,0.958333,0.941667,0.056519,8
7,0.008360,0.000949,0.005742,0.001101,30,linear,"{'C': 30, 'kernel': 'linear'}",0.958333,0.958333,0.833333,0.958333,1.000000,0.941667,0.056519,7

In [ ]:
results[['param_C',	'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.950000
1        1       linear         0.958333
2       10          rbf         0.958333
3       10       linear         0.950000
4       20          rbf         0.950000
5       20       linear         0.950000
6       30          rbf         0.941667
7       30       linear         0.941667

____________

**Now Use Random Search CV**

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
random_cv = RandomizedSearchCV((model_svm), {
    'C': [1,10,20,30],
    'kernel': ['rbf', 'linear'],
}, cv=5, return_train_score=False, n_iter=4)

In [ ]:
random_cv.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [ ]:
res = pd.DataFrame(random_cv.cv_results_)
res

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004012,0.000373,0.003136,0.000345,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,0.958333,0.833333,0.958333,1.000000,0.950000,0.061237,2
1,0.003914,0.000118,0.003227,0.000393,linear,20,"{'kernel': 'linear', 'C': 20}",0.958333,0.958333,0.833333,1.000000,1.000000,0.950000,0.061237,2
2,0.004235,0.000852,0.003138,0.000590,rbf,10,"{'kernel': 'rbf', 'C': 10}",1.000000,0.958333,0.833333,1.000000,1.000000,0.958333,0.064550,1
3,0.003735,0.000170,0.002956,0.000032,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.958333,0.958333,0.833333,1.000000,0.958333,0.941667,0.056519,4

In [ ]:
res[['param_kernel'	,'param_C','mean_test_score']]

  param_kernel  param_C  mean_test_score
0       linear       10         0.950000
1       linear       20         0.950000
2          rbf       10         0.958333
3          rbf       30         0.941667